name: Generate App Store Release Notes

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release_tag:
        description: "Release tag to generate notes for"
        required: false
        default: "latest"
      languages:
        description: "Comma-separated list of language codes (e.g., en,sv,fr,de)"
        required: false
        default: "en,sv,fr"

jobs:
  generate-release-notes:
    runs-on: ubuntu-latest
    # Add permissions for releases
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate App Store Release Notes
        id: release_notes
        uses: ./ # Or your published action path like: your-username/app-store-release-notes@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          release_tag: ${{ github.event.inputs.release_tag || 'latest' }}
          max_length: "450"
          languages: ${{ github.event.inputs.languages || 'en,sv,fr' }}

      - name: Display Preview
        run: |
          echo "====== COMBINED RELEASE NOTES ======"
          echo "${{ steps.release_notes.outputs.combined_release_notes }}"
          echo "===================================="

      - name: Save Release Notes
        run: |
          mkdir -p release-notes

          # Save directly from the combined output
          echo "${{ steps.release_notes.outputs.combined_release_notes }}" > release-notes/combined.md

      - name: Upload Release Notes to Release Assets
        run: |
          TAG_NAME="${{ github.event.inputs.release_tag || github.event.release.tag_name || 'latest' }}"
          if [ "$TAG_NAME" = "latest" ]; then
            TAG_NAME=$(gh release list --limit 1 --json tagName --jq '.[0].tagName')
          fi
          echo "Uploading release notes to tag: $TAG_NAME"
          gh release upload "$TAG_NAME" release-notes/combined.md --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
